version: "3.4"

services:
  PratoFeitoDb:
    image: postgres
    container_name: PratoFeitoDb
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=64"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_VOLUMES}:/var/lib/mysql"
    networks:
      - postgres-network

  PgAdmin:
    image: dpage/pgadmin4
    container_name: PgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_SENHA}
    ports:
      - "16543:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - postgres-network
    depends_on:
      - PratoFeitoDb

  LocalStack:
    image: localstack/localstack
    container_name: LocalStack
    ports:
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      - "127.0.0.1:9999:8080"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=futura
      - AWS_SECRET_ACCESS_KEY=131313
      - DEFAULT_REGION=us-east-1
      - SERVICES=sns,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCALSTACK_VOLUMES}:/var/tmp/localstack"      

networks:
  postgres-network:
    driver: bridge
    
volumes:
  pgadmin_data: